language: java

jdk:
- oraclejdk8

# sudo: required and dist: trusty selects an Ubuntu 14.04 VM with 7.5 GB RAM
sudo: required
dist: trusty

# unsupported by dist: trusty
#cache:
#  directories:
#  - $HOME/.m2

install:
- mvn -s .travis.maven.settings.xml -version -B
- which mvn
# - curl https://www.apache.org/dyn/closer.cgi?asjson=1 # returned http://mirrors.ibiblio.org/apache as preferred mirror
- export APACHE_MIRROR=http://mirrors.ibiblio.org/apache
- export MVN_VERSION=3.3.9
- pushd ~/
- wget $APACHE_MIRROR/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.tar.gz
- tar xfz apache-maven-$MVN_VERSION-bin.tar.gz
- chmod +x apache-maven-$MVN_VERSION/bin/mvn
- export M2_HOME=$PWD/apache-maven-$MVN_VERSION
- export PATH=$PWD/apache-maven-$MVN_VERSION/bin:${PATH}
- popd
- which mvn
- mvn -s .travis.maven.settings.xml -version -B
# unshallow is needed by license-maven-plugin
- git fetch origin --unshallow

before_script:
# we want 1) only log warning and errors, but info on the main CLI, so that we see what's being built atm. We also want to show the logger name of the maven log output, so that we can
# filter on it using our sed expression below.
- echo  "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.event.ExecutionEventLogger=info -Dorg.slf4j.simpleLogger.showLogName=true'" > ~/.mavenrc

script:
# here we go... our mighty sed filter explained:
# -n flag: print nothing unless specifically instructed to by the sed script
#
# s/^\\[INFO\\] org\\.apache\\.maven\\.cli\\.event\\.ExecutionEventLogger - \\( *[^ ].*\\)$/[INFO] \\1/p;
# print all [INFO] lines of the main Maven CLI logger (if there is any non-space after [INFO]). This is used to make sure that we see what is currently being built.
#
# /WARN/p;
# print any line that has "WARN" in it.
#
# /ERROR/p
# print any line that has "ERROR" in it.
#
# /^Tests run/p
# print the summary of the test results
#
# With this, we have the overview of what stage the build is currently in, yet we don't flood the output with stuff from tests and merely informative messages from the build.
#
- mvn -fae -s .travis.maven.settings.xml -Dsurefire.printSummary=false clean install -Pitest 2>&1 | sed -n 's/^\\[INFO\\] org\\.apache\\.maven\\.cli\\.event\\.ExecutionEventLogger - \\( *[^ ].*\\)$/[INFO] \\1/p; /WARN/p; /ERROR/p; /^Tests run/p'

env:
  global:
  - secure: g/PGmXBWEd9PgmP9xfuUj60yGdvGR9x9cRzE3EDkX0ALkAdZZxHpI3qWdNpUl9mNrtjrxM/4/yi7oKDOpkwl+iCw2KAvlfjnn8sWTEwDIfK9+zyFAU0C6QEJnkToLFvkumO4NbbBBGxQ2KR4rxaIDRI6umf3F8roZybTD+SLXfg=
  - secure: FlQ6i3L1vf5Gf73FMmEY8a0ZJpuQVzTwLjYlABbi5iJd+VQdlke3+5nEhEFYHKiiK6duye6GIxtti65s/VHS6VHJb62p/Z1Fj6/FsKgoFbVmzYenGDXEfGQYHnvCUm4OY/kcHIgeI5RpG2n0BXHRK9PSYfGD4G50i7ev7d0BnKw=
  # for pushing the swagger adoc documentation to the website repository
  - secure: fRgTtGRZRh1DhRIXlOnuWV6cROHhVvtNL3DzVay1zDnX0y0SVH3Aau/kbsytIkG4DaKvRi1XnI4sRC4HtUReXCMQjvwO9sdmj+9F3y04vbhH8qNR8IUBFADKjLCjjnq7Qo8PBbuk6b8Sj1bFpYSgd2sJXcvvA9cP/xlTMu6XZSM=
after_success:
- PROJECT_VERSION=`mvn --batch-mode org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
    mvn -s .travis.maven.settings.xml deploy -DskipTests ;
    ./.travis.swagger.sh ;
  fi
